# Site settings
title: "Ukaba Jimmy O - Data Analyst (Automation & ETL Focused)"
description: "Data Analytics portfolio showcasing machine learning projects and analysis"
author: "Ukaba Jimmy"
email: "jimmyukaba1234@gmail.com"

# Theme
theme: jekyll-theme-minimal

# Social links
Social linksgithub_username: https://github.com/jimmyukaba1234-prog
linkedin_username: www.linkedin.com/in/ukaba-jimmy-7b2b44267

# Enable GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Analytics (optional)
# google_analytics: G-XXXXXXXXXX
